# Generated by Django 3.2.14 on 2022-11-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_nome', models.CharField(max_length=255, null=True)),
                ('matricula', models.CharField(max_length=255, null=True)),
                ('codigo', models.CharField(max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField(auto_now=True)),
                ('participante', models.ManyToManyField(to='gerenciamento.Participante')),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField(auto_now=True)),
                ('participante', models.ManyToManyField(to='gerenciamento.Participante')),
            ],
        ),
    ]
