# Generated by Django 3.2.14 on 2022-11-06 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0002_participante_primeiro_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_entrada', models.DateTimeField(auto_now_add=True, null=True)),
                ('horario_saida', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='saida',
            name='participante',
        ),
        migrations.AlterField(
            model_name='participante',
            name='codigo',
            field=models.CharField(default='4KN3TQ9E', max_length=7, null=True),
        ),
        migrations.DeleteModel(
            name='Entrada',
        ),
        migrations.DeleteModel(
            name='Saida',
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='participante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacao', to='gerenciamento.participante'),
        ),
    ]
