# Generated by Django 3.2.14 on 2022-11-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0003_auto_20221106_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='codigo',
            field=models.CharField(default='S5EUE5FA', max_length=9, null=True),
        ),
    ]
