# Generated by Django 3.2.14 on 2022-11-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0004_alter_participante_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='status',
            field=models.CharField(choices=[('0', 'Ausente'), ('1', 'Presente'), ('2', 'Saída Antes do Horário Previsto')], default='1', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='horario_saida',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='codigo',
            field=models.CharField(default='XNOWG6SN', max_length=9, null=True),
        ),
    ]
