# Generated by Django 3.2.14 on 2022-11-06 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0005_auto_20221106_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimentacao',
            old_name='horario_saida',
            new_name='horario_retorno',
        ),
        migrations.RenameField(
            model_name='movimentacao',
            old_name='horario_entrada',
            new_name='horario_saida_antes',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='status',
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='status_movimentacao',
            field=models.CharField(choices=[('0', 'Saída Antes do Horário'), ('1', 'Retorno')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='status',
            field=models.CharField(choices=[('0', 'Ausente'), ('1', 'Presente')], default='0', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='codigo',
            field=models.CharField(default='CQV7BXVN', max_length=9, null=True),
        ),
        migrations.CreateModel(
            name='ConfirmarEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_entrada', models.DateTimeField(auto_now_add=True, null=True)),
                ('horario_saida', models.DateTimeField(auto_now=True, null=True)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmar', to='gerenciamento.participante')),
            ],
        ),
    ]
