# Generated by Django 3.2.14 on 2022-11-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0006_auto_20221106_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmarentrada',
            name='dia',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='status_movimentacao',
            field=models.CharField(choices=[('0', 'Saída Antes do Horário'), ('1', 'Retorno')], default='0', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='codigo',
            field=models.CharField(default='ZO1SN338', max_length=9, null=True),
        ),
    ]
